### ISSUE TITLE
Browser Processes Don't Quit If Test Failed

### ISSUE THREAD

**Issue by mikebronner** [orchestral/testbench-dusk#14]
Hi @Keoghan, I just wanted to follow up with you. I still have the issue that we talked about some time ago, where Chrome processes don't quit if the test fails.

To continue, I have to run the following manually: `killall Google\ Chrome`

**Comment by crynobone** [comment]
This is something that `laravel/dusk` does <https://github.com/laravel/dusk/blob/3.0/src/Concerns/ProvidesBrowser.php#L62-L81>

My assumption is that it would allow you to see what's going on when the tests failed.

**Comment by mikebronner** [comment]
Hi @crynobone, that would make sense if the browser is actually shown, but since it's running headless, seems like that is more of a problem.

So it seems I should be calling `$response->closeAll();` after my assertions to make sure it's all cleaned up. (Initial testing seems to support this.)

**Comment by mikebronner** [comment]
Update: the `closeAll` method won't be fired if the test stops processing. Need to look into this more closely -- seems to be a bit of a hairy area with Dusk. How do you handle orphaned browser processes?

**Comment by crynobone** [comment]
need @Keoghan why testbench-dusk uses --headless when Laravel Dusk doesn't

**Comment by Keoghan** [comment]
Hi folks, 

I think that Dusk since 2.0 uses headless as the default in the DuskTestcase - https://github.com/laravel/dusk/blob/3.0/stubs/DuskTestCase.stub

I’m not strongly opinionated either way but it does make the tests run a little quicker generally.

For the orphaned server processes I added a ‘register_shutdown’ function to close them (if still running) as the script is ended - which might work to do the same here. 

In non-headless it can be useful to poke around though.

I have an idea for making this a bit easier to administrate when choosing to go headless or not, so will pop that together and PR
